# /etc/greetd/config.toml
# Greeter: sysc-greet-hyprland
# https://github.com/Nomadcxx/sysc-greet

[terminal]
vt = 1

[default_session]
command = "start-hyprland -- --config /etc/greetd/hyprland-greeter-config.conf"
user = "greeter"
